[tool.poetry]
name = "comic-organizer"
version = "2.0.0"
description = ""
authors = ["Buried-In-Code"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
"ruamel.yaml" = "^0.17.10"
titlecase = "^2.3"
requests = "^2.26.0"
beautifulsoup4 = "^4.9.3"
lxml = "^4.6.3"
patool = "^1.12"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
comic-organizer = "comic-organizer:main"
