[tool.poetry]
name = "Dex-Starr"
version = "0.2.0"
description = "Helps sort and organize your comic collection by using the information stored in ComicInfo files."
license = "GPL-3.0-or-later"
authors = ["Buried-In-Code <BuriedInCode@tuta.io>"]
maintainers = ["Buried-In-Code <BuriedInCode@tuta.io>"]
readme = "README.md"
repository = "https://github.com/Buried-In-Code/Dex-Starr"
packages = [
	{ include = "dex_starr" }
]
include = [
	{ path = "tests", format = "sdist" }
]
classifiers = [
	"Development Status :: 5 - Alpha",
	"Environment :: Console",
	"Intended Audience :: End Users/Desktop",
	"License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
	"Natural Language :: English",
	"Operating System :: MacOS",
	"Operating System :: Microsoft :: Windows",
	"Operating System :: POSIX :: Linux",
	"Programming Language :: Python :: 3.8",
	"Programming Language :: Python :: 3.9",
	"Programming Language :: Python :: 3.10",
	"Topic :: Utilities",
	"Topic :: Other/Nonlisted Topic",
	"Typing :: Typed"
]
keywords = ["comics", "comic", "metadata", "tagging", "tagger"]

[tool.poetry.dependencies]
python = "^3.8"
jsonschema = "^4.3.2"
mokkari = "^2.0.0"
pathvalidate = "^2.5.0"
patool = "^1.12"
ratelimit = "^2.2.1"
requests = "^2.26.0"
rich = "^10.16.1"
"ruamel.yaml" = "^0.17.17"
simyan = "^0.7.0"
xmltodict = "^0.12.0"
yamale = "^4.0.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
tox = "^3.24.4"
pre-commit = "^2.16.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
Dex-Starr = 'dex_starr.__main__:main'

[tool.poetry.urls]
"Issue Tracker" = "https://github.com/Buried-In-Code/Dex-Starr/issues"

[tool.black]
line-length = 120
target-version = ['py38']

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
default_section = "THIRDPARTY"
known_first_party = []
known_third_party = []

[tool.coverage.run]
source = ["dex_starr"]

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
addopts = ["--cov", "-x"]
