[tool.poetry]
name = "Dex-Starr"
version = "0.1.0"
description = "Helps sort and organize your comic collection by using the information stored in ComicInfo files."
license = "GPL-3.0-or-later"
authors = ["Buried-In-Code <6057651+Buried-In-Code@users.noreply.github.com>"]
maintainers = ["Buried-In-Code <6057651+Buried-In-Code@users.noreply.github.com>"]
readme = "README.md"
repository = "https://github.com/Buried-In-Code/Dex-Starr"
packages = [
	{ include = "DexStarr" }
]
include = [
	{ path = "tests", format = "sdist" }
]
classifiers = [
	"Development Status :: 4 - Beta",
	"Environment :: Console",
	"Intended Audience :: End Users/Desktop",
	"License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
	"Natural Language :: English",
	"Operating System :: MacOS",
	"Operating System :: Microsoft :: Windows",
	"Operating System :: POSIX :: Linux",
	"Programming Language :: Python :: 3.8",
	"Programming Language :: Python :: 3.9",
	"Topic :: Utilities",
	"Topic :: Other/Nonlisted Topic",
	"Typing :: Typed"
]
keywords = ["comics", "comic", "metadata", "tagging", "tagger"]

[tool.poetry.dependencies]
python = "^3.8"
Painted-Logger = "^1.3.0"
"ruamel.yaml" = "^0.17.14"
titlecase = "^2.3"
requests = "^2.26.0"
ratelimit = "^2.2.1"
beautifulsoup4 = "^4.10.0"
lxml = "^4.6.3"
patool = "^1.12"
colorama = "^0.4.4"
mokkari = "^0.2.4"
simyan = "^0.5.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^2.12.1"
flake8 = "^3.9.2"
black = "^21.8b0"
isort = "^5.9.3"
pre-commit = "^2.15.0"
pyupgrade = "^2.26.0"
seed-isort-config = "^2.2.0"
tox = "^3.24.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Issue Tracker" = "https://github.com/Buried-In-Code/Dex-Starr/issues"

[tool.black]
line-length = 120
target-version = ['py38']

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
default_section = "THIRDPARTY"
known_first_party = []
known_third_party = ["Simyan", "bs4", "colorama", "mokkari", "painted_logger", "patoolib", "pytest", "ratelimit", "requests", "ruamel", "titlecase"]

[tool.coverage.run]
source = ["DexStarr"]

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
addopts = ["--cov", "-x"]

