Output Format: enum('Json', 'Xml', 'Yaml')
Delete Extras: bool()
Resolution Order: list(str())
Folders:
  Import: str()
  Processing: str()
  Collection: str()
Comicvine:
  API Key: any(str(), null())
League of Comic Geeks:
  API Key: any(str(), null())
  Client ID: any(str(), null())
Metron:
  Username: any(str(), null())
  Password: any(str(), null())
