name: Update dependencies

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v3
      #----------------------------------------------
      - name: Update dependencies
        uses: pdm-project/update-deps-action@v1
        with:
          update-strategy: all
          pr-title: "[PDM Action] Update dependencies"
